
* Debugging Tools

** Libraries for debugging code.

pdb-like Debugger
ipdb - IPython-enabled pdb.
pdb++ - Another drop-in replacement for pdb.
pudb - A full-screen, console-based Python debugger.
remote-pdb - Remote vanilla PDB (over TCP sockets).
wdb - An improbable web debugger through WebSockets.

** Profiler
line_profiler - Line-by-line profiling.
memory_profiler - Monitor Memory usage of Python code.
Pyflame - Attach this Ptracing Profiler to any processes running Python. Perfect for profiling production webservers.
profiling - An interactive Python profiler.
vprof - Visual Python profiler.

** Others
IceCream - Inspect variables, expressions, and program execution with a single, simple function call.
django-debug-toolbar - Display various debug information for Django.
django-devserver - A drop-in replacement for Django's runserver.
flask-debugtoolbar - A port of the django-debug-toolbar to flask.
hunter - Hunter is a flexible code tracing toolkit.
lptrace - strace for Python programs.
manhole - Debug service that will accept unix domain socket connections and present the stacktraces for all threads and an interactive prompt.
pyelftools - Parsing and analyzing ELF files and DWARF debugging information.
pyringe - Debugger capable of attaching to and injecting code into Python processes.
