* Web Content Extracting

Libraries for extracting web contents.

Haul - An Extensible Image Crawler.
html2text - Convert HTML to Markdown-formatted text.
lassie - Web Content Retrieval for Humans.
micawber - A small library for extracting rich content from URLs.
newspaper - News extraction, article extraction and content curation in Python.
python-goose - HTML Content/Article Extractor.
python-readability - Fast Python port of arc90's readability tool.
requests-html - Pythonic HTML Parsing for Humans.
sanitize - Bringing sanity to world of messed-up data.
sumy - A module for automatic summarization of text documents and HTML pages.
textract - Extract text from any document, Word, PowerPoint, PDFs, etc.
toapi - Every web site provides APIs.


* Web Crawling & Web Scraping

Libraries to automate data extraction from websites.

cola - A distributed crawling framework.
Demiurge - PyQuery-based scraping micro-framework.
feedparser - Universal feed parser.
Grab - Site scraping framework.
MechanicalSoup - A Python library for automating interaction with websites.
portia - Visual scraping for Scrapy.
pyspider - A powerful spider system.
RoboBrowser - A simple, Pythonic library for browsing the web without a standalone web browser.
Scrapy - A fast high-level screen scraping and web crawling framework.


* Web Frameworks

Full stack web frameworks.

Django - The most popular web framework in Python.
awesome-django
Flask - A microframework for Python.
awesome-flask
Pyramid - A small, fast, down-to-earth, open source Python web framework.
awesome-pyramid
Sanic - Web server that's written to go fast.
Tornado - A Web framework and asynchronous networking library.
Vibora - Fast, efficient and asynchronous Web framework inspired by Flask.



* Libraries for working with WebSocket.

AutobahnPython - WebSocket & WAMP for Python on Twisted and asyncio.
Crossbar - Open-source Unified Application Router (Websocket & WAMP for Python on Autobahn).
django-channels - Developer-friendly asynchrony for Django.
django-socketio - WebSockets for Django.
WebSocket-for-Python - WebSocket client and server library for Python 2 and 3 as well as PyPy.
